version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    user: root

    ports:
      - "8080:8080"
      - "50000:50000"

    volumes:
      - jenkins_home:/var/jenkins_home
      # Windows uses named pipe instead of Unix socket
      - type: npipe
        source: \\.\pipe\docker_engine
        target: /var/run/docker.sock

    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped

volumes:
  jenkins_home:
    driver: local